/*
 * This file is automatically generated by UnitTestBot. For further information seehttps://unittestbot.org
 */

#define main main__
#include "../../../../../lib/structures/structs/simple_structs.c"
int get_sign_struct_lib_structures_structs_simple_structs_c(struct MyStruct st) {
return get_sign_struct(st);
}
int calculate_something_lib_structures_structs_simple_structs_c(struct OneMoreStruct str) {
return calculate_something(str);
}
char get_symbol_by_struct_lib_structures_structs_simple_structs_c(const struct StructWithChars st) {
return get_symbol_by_struct(st);
}
signed char operate_with_inner_structs_lib_structures_structs_simple_structs_c(struct MainStruct st) {
return operate_with_inner_structs(st);
}
struct MainStruct struct_as_return_type_lib_structures_structs_simple_structs_c(int a) {
return struct_as_return_type(a);
}
struct StructWithUnion struct_with_union_as_return_type_lib_structures_structs_simple_structs_c(int t) {
return struct_with_union_as_return_type(t);
}
struct A complex_struct_with_union_as_return_type_lib_structures_structs_simple_structs_c(int t) {
return complex_struct_with_union_as_return_type(t);
}
struct StructWithUnionInUnion struct_with_union_in_union_as_return_type_lib_structures_structs_simple_structs_c(int a, int b) {
return struct_with_union_in_union_as_return_type(a, b);
}
struct StructWithStructInUnion struct_with_struct_in_union_as_return_type_lib_structures_structs_simple_structs_c(int a, int b) {
return struct_with_struct_in_union_as_return_type(a, b);
}
