/*
 * This file is automatically generated by UnitTestBot. For further information seehttps://unittestbot.org
 */

#define main main__
#include "../../../../lib/module/libfunc.c"
int libfunc_lib_module_libfunc_c(int a) {
return libfunc(a);
}
