// 1664808001000000000
// Please, do not change the line above

/*
 * This file is automatically generated by UnitTestBot. For further information see https://www.utbot.org
 */

#ifdef KLEE_MODE
extern void klee_make_symbolic(void *addr, unsigned long long nbytes, const char *name);
#endif
#include "main_stub.h"

#define NULL ((void*)0)

int foo12_symbolic[10];
int _foo12_symbolic[10];
int foo12(int x) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&_foo12_symbolic, sizeof(_foo12_symbolic), "_foo12_symbolic");
            for (int it_2_0 = 0; it_2_0 < 10; it_2_0 ++) {
                klee_prefer_cex(_foo12_symbolic, _foo12_symbolic[it_2_0] >= -10 & _foo12_symbolic[it_2_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return _foo12_symbolic[cntCall++];
}


int opp_symbolic[10];
int _opp_symbolic[10];
int opp(int x) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&_opp_symbolic, sizeof(_opp_symbolic), "_opp_symbolic");
            for (int it_3_0 = 0; it_3_0 < 10; it_3_0 ++) {
                klee_prefer_cex(_opp_symbolic, _opp_symbolic[it_3_0] >= -10 & _opp_symbolic[it_3_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return _opp_symbolic[cntCall++];
}


int main_symbolic[10];
int _main_symbolic[10];
int main(int argc, char ** argv) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&_main_symbolic, sizeof(_main_symbolic), "_main_symbolic");
            for (int it_4_0 = 0; it_4_0 < 10; it_4_0 ++) {
                klee_prefer_cex(_main_symbolic, _main_symbolic[it_4_0] >= -10 & _main_symbolic[it_4_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return _main_symbolic[cntCall++];
}


