/*
 * This file is automatically generated by UnitTestBot. For further information seehttps://unittestbot.org
 */

#define main main__
#include "../../../lib/basic_functions.c"
int max__lib_basic_functions_c(int a, int b) {
return max_(a, b);
}
int min_lib_basic_functions_c(int a, int b) {
return min(a, b);
}
int sqr_positive_lib_basic_functions_c(int a) {
return sqr_positive(a);
}
int simple_loop_lib_basic_functions_c(unsigned int n) {
return simple_loop(n);
}
