/*
 * This file is automatically generated by UnitTestBot. For further information seehttps://unittestbot.org
 */

#define main main__
#include "../../../lib/main.c"
int exit_code_lib_main_c(int argc) {
return exit_code(argc);
}
int main2_lib_main_c(int argc, char **argv) {
return main2(argc, argv);
}
int main_lib_main_c(int argc, char **argv) {
return main(argc, argv);
}
