/*
 * This file is automatically generated by UnitTestBot. For further information seehttps://unittestbot.org
 */

#include "main_dot_c_test.h"

#include "gtest/gtest.h"
namespace UTBot {
static const float utbot_abs_error = 1e-6;


#pragma region regression
TEST(regression, foo_test_1)
{
    int actual = foo(-1);
    EXPECT_EQ(-1, actual);
}

#pragma endregion
#pragma region error
TEST(error, foo_test_2)
{
    foo(0);
}

TEST(error, main_test_1)
{
    char _argv[2][2] = {{'c', 'c'}, {'c', 'b'}};
    char ** argv = (char **) calloc(3, sizeof(char *));
    for (int it_7_0 = 0; it_7_0 < 2; it_7_0 ++) {
        argv[it_7_0] = _argv[it_7_0];
    }
    argv[2] = NULL;
    main(0, argv);
}

#pragma endregion
}
