/*
 * This file is automatically generated by UnitTestBot. For further information seehttps://unittestbot.org
 */

#include "simple_calc_dot_c_test.h"

#include "gtest/gtest.h"
namespace UTBot {
static const float utbot_abs_error = 1e-6;


#pragma region regression
TEST(regression, f_test_1)
{
    int actual = f(0);
    EXPECT_EQ(0, actual);
}

TEST(regression, other_module_call_test_1)
{
    int actual = other_module_call(0);
    EXPECT_EQ(1, actual);
}

#pragma endregion
}
