/*
 * This file is automatically generated by UnitTestBot. For further information see https://www.utbot.org
 */

#include "libfunc_dot_c_test.h"

#include "gtest/gtest.h"
namespace UTBot {


#pragma region regression
TEST(regression, libfunc11_test_1)
{
    int actual = libfunc11(2);
    EXPECT_EQ(0, actual);
}

#pragma endregion
#pragma region error
TEST(error, libfunc11_test_2)
{
    libfunc11(0);
}

#pragma endregion
}
