/*
 * This file is automatically generated by UnitTestBot. For further information seehttps://unittestbot.org
 */

#define main main__
#include "../../main.c"
int main_main_c(int argc, char *argv[]) {
return main(argc, argv);
}
