/*
 * This file is automatically generated by UnitTestBot. For further information seehttps://unittestbot.org
 */

#define main main__
#include "../../../src/main.c"
int foo12_src_main_c(int x) {
return foo12(x);
}
int opp_src_main_c(int x) {
return opp(x);
}
int main_src_main_c(int argc, char *argv[]) {
return main(argc, argv);
}
