/*
 * This file is automatically generated by UnitTestBot. For further information seehttps://unittestbot.org
 */

#define main main__
#include "../../../src/simple_calc.c"
int f_src_simple_calc_c(int a) {
return f(a);
}
int other_module_call_src_simple_calc_c(int a) {
return other_module_call(a);
}
