name: "Run UTBotCpp-action"

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: UTBot code analysis
#      uses: UnitTestBot/UTBotCpp-action@test-1.0.26
      uses: alexey-utkin/UTBotCpp-action@1.0.36
      with:
        add_tests: 'false'
        refresh_tests: 'false'
        utbot_version: '2022.10.3'
        scope: 'project'
#        scope: 'file'
#        path: 'src/main.c'
        runtests: 'false'
